// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWdo3vBP9BReQburSMu-nMcOYM1hfX6XQ',
    appId: '1:369971324988:web:2a903b365da21be6737b39',
    messagingSenderId: '369971324988',
    projectId: 'farmeasy-f7ebc',
    authDomain: 'farmeasy-f7ebc.firebaseapp.com',
    storageBucket: 'farmeasy-f7ebc.appspot.com',
    measurementId: 'G-GEE44BZ79E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeiSwuKkh39hGyldqk37wl72xNOLT5de4',
    appId: '1:369971324988:android:b0ae31a21e999dae737b39',
    messagingSenderId: '369971324988',
    projectId: 'farmeasy-f7ebc',
    storageBucket: 'farmeasy-f7ebc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRjmgSwGAjnINuiOi5fSD_4wP-NuY67Fs',
    appId: '1:369971324988:ios:0227cdd8b2963982737b39',
    messagingSenderId: '369971324988',
    projectId: 'farmeasy-f7ebc',
    storageBucket: 'farmeasy-f7ebc.appspot.com',
    iosBundleId: 'ai.farmeasy.codenicely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRjmgSwGAjnINuiOi5fSD_4wP-NuY67Fs',
    appId: '1:369971324988:ios:1f4ccb2c1abf0b44737b39',
    messagingSenderId: '369971324988',
    projectId: 'farmeasy-f7ebc',
    storageBucket: 'farmeasy-f7ebc.appspot.com',
    iosBundleId: 'com.example.farmEasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWdo3vBP9BReQburSMu-nMcOYM1hfX6XQ',
    appId: '1:369971324988:web:0c9b9dcc76ac5b59737b39',
    messagingSenderId: '369971324988',
    projectId: 'farmeasy-f7ebc',
    authDomain: 'farmeasy-f7ebc.firebaseapp.com',
    storageBucket: 'farmeasy-f7ebc.appspot.com',
    measurementId: 'G-HN6BSH33Z9',
  );

}